### ISSUE TITLE
CppBLLoader cannot be imported

### ISSUE THREAD

**Issue by hwiedDFKI** [rock-learning/bolero#97]
Under python3 the import `from ._wrapper import CppBLLoader` in bolero/wrapper/\_\_init\_\_.py fails.
Therefore I can't create a controller instance from a dict. The config works for `bolero_controller`
```
from bolero.controller import Controller
cfg = yaml.load(open("../learning_config.yml"))
Controller(cfg)
```
Did I miss to install something?
exported PYTHON and CYTHON to version 3, did cmake .., make install in build, also did python3 setup.py install

**Comment by AlexanderFabisch** [comment]
Sorry for the late reply. The wrapper needs to be configured before bolero's Python lib is installed:

    bob-bootstrap learning/bolero/bolero/wrapper

Would that work?

**Comment by AlexanderFabisch** [comment]
Some details: the subproject learning/bolero/bolero/wrapper generates a file called `build_info.py`. The environment variables PYTHON and CYTHON have to be defined when you build this subproject. In the next step we would actually build and install the wrapper. It is part of BOLeRo's Python packages (lerning/bolero/).

**Comment by AlexanderFabisch** [comment]
This issue should now be fixed completely with the latest version of pybob. If you export the environment variables and run `bob-envsh` it should write the environment variables to your env.sh and the aliases for pybob should be called with Python 3.

Any news from your side? If not, I will assume that this issue is solved...

**Comment by hwiedDFKI** [comment]
Great. Thanks for your help!
